version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"

  # Maintain dependencies for Python backend
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Next.js frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
